# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tag_list',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
    ]
