# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='abstract',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
