# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_content_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='abstract',
            field=models.TextField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
