# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('imgPath', models.CharField(max_length=128)),
                ('gitHubLink', models.CharField(max_length=128)),
                ('demoLink', models.CharField(max_length=128)),
                ('blogRoute', models.CharField(max_length=128)),
            ],
        ),
    ]
